### ISSUE TITLE
Derive all necessary equations

### ISSUE THREAD

**Issue by wayne-wu** [wayne-wu/wiggly#7]
While the authors of the paper have outlined the main implementation steps, some mathematical equations are ambiguously stated and must be derived and understood first before implementation. We may reach out to the authors for any further clarifications. Some ambigously stated techniques include: Finding the exact closed form of the integral part of the energy function, the inclusion of the boundary constraints in the matrix $A$, and the elimination of all linear constraints using to reduce the final search space via singular value decomposition.

**Comment by aiyopasta** [comment]
- [ ] Find exact closed form of integral part of energy function
- [ ] Derive large wiggly spline matrix-vector equation
- [ ] Find out how to include boundary constraints in large matrix-vector equation
- [ ] Find out how to use SVD to eliminate linear constraints to reduce final search space
